server:
  port: 9080
spring:
  datasource:
    url: jdbc:mysql://47.104.94.75:3306/polar-im?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    useColumnLabel: true
    useGeneratedKeys: true
file:
  smms:
    host: https://sm.ms/api/v2/upload
    token: PoNnZbHxVoZw4Nxp3UumyuPw5Yu1jbia
#  qiniu:
#    host: http://q7jq4gl0w.bkt.clouddn.com/
#    access-key: jp_Z0zTMcE0JeBgHmmyQzyhSgFH1FkFI6_FuMR-D
#    secret-key: aWtZ1KL6FZtlG_5_2zgVprwhvJSqTuxdaz8AZ4KA
#    bucket: polar-image
#  ftp:
#    ip: 47.104.94.75
#    port: 21
#    user: aias
#    pass: 123456
#    file-path: /Data/fileUpload/

jwt:
  #JWT秘钥
  secret: JustWannaU
  #JWT有效期（毫秒），默认15天
  expiration: 1296000000
  # 加密算法
  signature-algorithm-name: HS512
  # 不需要验证的请求路径
  exclude-path-patterns: /**/login, /**/check, /**/register


logging:
  level:
    com.aias.polar.im.server.dao: debug